### ISSUE TITLE
Support pyproject.toml

### ISSUE THREAD

**Issue by benregn** [asottile/seed-isort-config#17]
Since `isort` now supports reading configuration from `pyproject.toml`, should support for it be added here?

**Comment by asottile** [comment]
Makes sense to me! Would you be interested in working on this?

**Comment by gmacon** [comment]
I may take a look at this. One question before I start:

isort has an optional dependency on the [toml](https://pypi.org/project/toml/) library for parsing pyproject.toml, but I think it would be better to use the [tomlkit](https://pypi.org/project/tomlkit/) library instead here because it allows modifying the document while preserving formatting and comments. Does that sound reasonable to you?

**Comment by asottile** [comment]
Currently `seed-isort-config` doesn't actually load the configuration file at all -- just does some text parsing.  Ideally if we could keep doing that that would be best (since then we don't have to worry about the semantics of the actual document, substitutions, dependencies, etc.)

**Comment by gmacon** [comment]
OK. In that case, we probably need to restrict what subset of TOML we support. I'd probably generate output like this:

```toml
known_third_party = ["click", "requests"]
```

and require the input to be in that same format, i.e. a single line with single-double-quoted strings.

**Comment by asottile** [comment]
Cool, you can probably use `ast.literal_eval` to parse and unparse in that case :+1:
