### ISSUE TITLE
Skip files that fail to parse their AST

### ISSUE THREAD

**Issue by TheButlah** [asottile/seed-isort-config#59]
Currently this hook fails if it attempts to parse a python file that has invalid syntax. This means that a side-effect of this hook is requiring all files in the repository to be valid python. This seems like a large limitation of the hook - imports don't need to be sorted in files that don't parse, and we don't necessarily want code being checked as a side effect.

Would it be possible to just ignore files that fail to parse?

**Comment by asottile** [comment]
there is an intended interface for this -- use `--exclude=regular_expression` (usually with `args: [...]` if you're configuring this with pre-commit)

**Comment by TheButlah** [comment]
I'm making good use of said argument already - I have used it to exclude experimental directories. However it's not sufficient for my use case, as I don't want to require files elsewhere to parse

**Comment by asottile** [comment]
why would you need to check in python files which don't parse?

**Comment by TheButlah** [comment]
I work in a research lab - people don't always ensure that committed code works. We have instead specific directories and projects that have tests and are required to work. That being said, we are trying to improve the code quality and adding formatters and import organizers is important towards this goal, which is why I would like to use this hook without having to simultaneously enforce that all code must parse.

**Comment by asottile** [comment]
I think requiring python code to _parse_ is a pretty basic requirement for committing so I'm not going to extend this to silently ignore broken code

**Comment by TheButlah** [comment]
I understand your stance and while I philosophically agree, it's not that straightforward in practice. If you are the sort of person that believes in the importance of good code quality, you should know that preventing people from adopting tools that will help them move towards that goal is counterproductive.

But it's your tool, you do you.

**Comment by asottile** [comment]
you're always free to fork and add your own behaviours, pre-commit actually makes this way easier than normal python projects because it uses `git` as the underlying protocol

so if you want, you could temporarily add that feature and use your fork while you work to improve the code quality of your repository -- and once you have better enforcement in place, you can then switch back to this

asking me to add a feature which goes against some basic principles and then support that feature forever for a usecase that I don't agree with is where I'm drawing the line above -- hopefully that makes sense.  "No is temporary, Yes is forever"

**Comment by TheButlah** [comment]
I suppose forking makes sense here. Thanks for the rapid responses, and regardless I appreciate the tool and will continue to use it if possible.
