### ISSUE TITLE
Split config across multiple lines to reduce git churn

### ISSUE THREAD

**Issue by olirice** [asottile/seed-isort-config#73]
For larger projects `.isort.cfg` is a constant source of merge conflicts

Is there a way to populate the known third party list with 1 package per line to reduce git churn & make it easier to see which packages were added/removed?

**Comment by asottile** [comment]
Dupe of #45

but also I'm probably going to stop maintenance of this tool as it is no longer necessary in isort 5 (if I read the changelog correctly, I haven't actually verified this myself because I do not use isort, I use [reorder-python-imports](https://github.com/asottile/reorder_python_imports))

**Comment by asottile** [comment]
you can also use `git diff --word-diff` which makes it easy to see what was added and removed

**Comment by olirice** [comment]
Thanks for the info, upgrading from isort 4 to 5 solved it
